apiVersion: v1
kind: Template

parameters:

- name: JOB_NAME
  value: ""

- name: SOURCE_GIT_URI
  value: ""

- name: SOURCE_GIT_DIR
  value: /

- name: SOURCE_GIT_REF
  value: master

- name: OUTPUT_IMAGE
  value: ""

objects:

- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${JOB_NAME}
  spec:
    output:
      pushSecret:
        name: dockerhub
      to:
        kind: DockerImage
        name: ${OUTPUT_IMAGE}
    source:
      contextDir: ${SOURCE_GIT_DIR}
      git:
        ref: ${SOURCE_GIT_REF}
        uri: ${SOURCE_GIT_URI}
      type: Git
    strategy:
      dockerStrategy:
        noCache: true
      type: Docker
    triggers:
    - type: ConfigChange
